import { OrderStatusView } from './orders.models';

export const ORDER_STATUS_CATALOG: readonly OrderStatusView[] = [
  { code: 1, label: 'ACTIVO', tone: 'brand' },
  { code: 49, label: 'ACTIVOEN_PREPARACION', tone: 'gold' },
  { code: 48, label: 'ACTIVOEN_TRANSPORTE', tone: 'gold' },
  { code: 50, label: 'ADMITIDA', tone: 'gold' },
  { code: 46, label: 'ALISTADO', tone: 'gold' },
  { code: 2, label: 'ANULADO', tone: 'neutral' },
  { code: 60, label: 'ANULADOEN_REPARTO', tone: 'neutral' },
  { code: 59, label: 'ANULADOINCIDENTE', tone: 'neutral' },
  { code: 3, label: 'CANCELADO', tone: 'neutral' },
  { code: 26, label: 'CIUDAD_DESTINO', tone: 'gold' },
  { code: 27, label: 'CIUDAD_ORIGEN', tone: 'gold' },
  { code: 54, label: 'CLIENTE NO PAGA', tone: 'neutral' },
  { code: 4, label: 'DESPACHADA', tone: 'gold' },
  { code: 28, label: 'DESTINATARIO RECIBE EN FECHA U HORARIO ESPECIFICO', tone: 'gold' },
  { code: 5, label: 'DEVOLUCION', tone: 'neutral' },
  { code: 56, label: 'DEVOLUCION EN BODEGA', tone: 'neutral' },
  { code: 6, label: 'EN BODEGA DESTINO', tone: 'gold' },
  { code: 40, label: 'EN BODEGA DROPI', tone: 'gold' },
  { code: 7, label: 'EN BODEGA ORIGEN', tone: 'gold' },
  { code: 8, label: 'EN BODEGA TRANSPORTADORA', tone: 'gold' },
  { code: 29, label: 'EN CAMINO DE REGRESO A DEVOLUCION', tone: 'neutral' },
  { code: 30, label: 'EN DESPACHO', tone: 'gold' },
  { code: 31, label: 'EN DISTRIBUCION', tone: 'gold' },
  { code: 32, label: 'EN EMPAQUE', tone: 'gold' },
  { code: 9, label: 'EN ESPERA DE RUTA DOMESTICA', tone: 'gold' },
  { code: 10, label: 'EN PROCESAMIENTO', tone: 'gold' },
  { code: 33, label: 'EN RECIBO', tone: 'gold' },
  { code: 11, label: 'EN REEXPEDICION', tone: 'gold' },
  { code: 12, label: 'EN REPARTO', tone: 'gold' },
  { code: 13, label: 'EN TERMINAL DESTINO', tone: 'gold' },
  { code: 14, label: 'EN TERMINAL ORIGEN', tone: 'gold' },
  { code: 51, label: 'EN TRANSITO', tone: 'gold' },
  { code: 34, label: 'EN TRANSPORTE', tone: 'gold' },
  { code: 36, label: 'EN_REPARTO', tone: 'gold' },
  { code: 15, label: 'ENTREGADO', tone: 'mint' },
  { code: 16, label: 'ENTREGADO A TRANSPORTADORA', tone: 'mint' },
  { code: 17, label: 'GUIA_ANULADA', tone: 'neutral' },
  { code: 18, label: 'GUIA_GENERADA', tone: 'brand' },
  { code: 45, label: 'INDEMNIZACIÓN PAGADA', tone: 'mint' },
  { code: 41, label: 'INDEMNIZADA', tone: 'neutral' },
  { code: 42, label: 'INDEMNIZADA POR DROPI', tone: 'neutral' },
  { code: 61, label: 'INDEMNIZADA POR PARTNERSHOP', tone: 'neutral' },
  { code: 19, label: 'INTENTO DE ENTREGA', tone: 'gold' },
  { code: 43, label: 'LOST', tone: 'neutral' },
  { code: 53, label: 'NO SE LOCALIZA DIRECCIÓN DEL DESTINATARIO', tone: 'neutral' },
  { code: 20, label: 'NOVEDAD', tone: 'neutral' },
  { code: 21, label: 'NOVEDAD SOLUCIONADA', tone: 'mint' },
  { code: 55, label: 'PEDIDO CANCELADO', tone: 'neutral' },
  { code: 22, label: 'PENDIENTE', tone: 'brand' },
  { code: 35, label: 'POR RECOLECTAR', tone: 'brand' },
  { code: 37, label: 'PUNTO_DROOP', tone: 'gold' },
  { code: 23, label: 'RECHAZADO', tone: 'neutral' },
  { code: 47, label: 'RECLAMACIONES', tone: 'neutral' },
  { code: 24, label: 'RECLAME EN OFICINA', tone: 'neutral' },
  { code: 44, label: 'RECOGIDA FALLIDA', tone: 'neutral' },
  { code: 58, label: 'RECOGIDO POR DROPI', tone: 'mint' },
  { code: 52, label: 'REENVIO', tone: 'gold' },
  { code: 25, label: 'SIN MOVIMIENTOS', tone: 'neutral' },
  { code: 38, label: 'SINIESTRADO', tone: 'neutral' },
  { code: 39, label: 'TELEMERCADEO', tone: 'brand' },
] as const;

export const ORDER_STATUS_MAP = new Map(
  ORDER_STATUS_CATALOG.map((status) => [status.code, status] as const),
);
