import { OrderStatusView } from './orders.models';

export const ORDER_STATUS_CATALOG: readonly OrderStatusView[] = [
  { code: 'ACTIVO', label: 'ACTIVO', tone: 'brand' },
  { code: 'ACTIVOEN_PREPARACION', label: 'ACTIVOEN_PREPARACION', tone: 'gold' },
  { code: 'ACTIVOEN_TRANSPORTE', label: 'ACTIVOEN_TRANSPORTE', tone: 'gold' },
  { code: 'ADMITIDA', label: 'ADMITIDA', tone: 'gold' },
  { code: 'ALISTADO', label: 'ALISTADO', tone: 'gold' },
  { code: 'ANULADO', label: 'ANULADO', tone: 'neutral' },
  { code: 'ANULADOEN_REPARTO', label: 'ANULADOEN_REPARTO', tone: 'neutral' },
  { code: 'ANULADOINCIDENTE', label: 'ANULADOINCIDENTE', tone: 'neutral' },
  { code: 'CANCELADO', label: 'CANCELADO', tone: 'neutral' },
  { code: 'CIUDAD_DESTINO', label: 'CIUDAD_DESTINO', tone: 'gold' },
  { code: 'CIUDAD_ORIGEN', label: 'CIUDAD_ORIGEN', tone: 'gold' },
  { code: 'CLIENTE NO PAGA', label: 'CLIENTE NO PAGA', tone: 'neutral' },
  { code: 'DESPACHADA', label: 'DESPACHADA', tone: 'gold' },
  { code: 'DESTINATARIO RECIBE EN FECHA U HORARIO ESPECIFICO', label: 'DESTINATARIO RECIBE EN FECHA U HORARIO ESPECIFICO', tone: 'gold' },
  { code: 'DEVOLUCION', label: 'DEVOLUCION', tone: 'neutral' },
  { code: 'DEVOLUCION EN BODEGA', label: 'DEVOLUCION EN BODEGA', tone: 'neutral' },
  { code: 'EN BODEGA DESTINO', label: 'EN BODEGA DESTINO', tone: 'gold' },
  { code: 'EN BODEGA DROPI', label: 'EN BODEGA DROPI', tone: 'gold' },
  { code: 'EN BODEGA ORIGEN', label: 'EN BODEGA ORIGEN', tone: 'gold' },
  { code: 'EN BODEGA TRANSPORTADORA', label: 'EN BODEGA TRANSPORTADORA', tone: 'gold' },
  { code: 'EN CAMINO DE REGRESO A DEVOLUCION', label: 'EN CAMINO DE REGRESO A DEVOLUCION', tone: 'neutral' },
  { code: 'EN DESPACHO', label: 'EN DESPACHO', tone: 'gold' },
  { code: 'EN DISTRIBUCION', label: 'EN DISTRIBUCION', tone: 'gold' },
  { code: 'EN EMPAQUE', label: 'EN EMPAQUE', tone: 'gold' },
  { code: 'EN ESPERA DE RUTA DOMESTICA', label: 'EN ESPERA DE RUTA DOMESTICA', tone: 'gold' },
  { code: 'EN PROCESAMIENTO', label: 'EN PROCESAMIENTO', tone: 'gold' },
  { code: 'EN RECIBO', label: 'EN RECIBO', tone: 'gold' },
  { code: 'EN REEXPEDICION', label: 'EN REEXPEDICION', tone: 'gold' },
  { code: 'EN REPARTO', label: 'EN REPARTO', tone: 'gold' },
  { code: 'EN TERMINAL DESTINO', label: 'EN TERMINAL DESTINO', tone: 'gold' },
  { code: 'EN TERMINAL ORIGEN', label: 'EN TERMINAL ORIGEN', tone: 'gold' },
  { code: 'EN TRANSITO', label: 'EN TRANSITO', tone: 'gold' },
  { code: 'EN TRANSPORTE', label: 'EN TRANSPORTE', tone: 'gold' },
  { code: 'EN_REPARTO', label: 'EN_REPARTO', tone: 'gold' },
  { code: 'ENTREGADO', label: 'ENTREGADO', tone: 'mint' },
  { code: 'ENTREGADO A TRANSPORTADORA', label: 'ENTREGADO A TRANSPORTADORA', tone: 'mint' },
  { code: 'GUIA_ANULADA', label: 'GUIA_ANULADA', tone: 'neutral' },
  { code: 'GUIA_GENERADA', label: 'GUIA_GENERADA', tone: 'brand' },
  { code: 'INDEMNIZACIÓN PAGADA', label: 'INDEMNIZACIÓN PAGADA', tone: 'mint' },
  { code: 'INDEMNIZADA', label: 'INDEMNIZADA', tone: 'neutral' },
  { code: 'INDEMNIZADA POR DROPI', label: 'INDEMNIZADA POR DROPI', tone: 'neutral' },
  { code: 'INDEMNIZADA POR PARTNERSHOP', label: 'INDEMNIZADA POR PARTNERSHOP', tone: 'neutral' },
  { code: 'INTENTO DE ENTREGA', label: 'INTENTO DE ENTREGA', tone: 'gold' },
  { code: 'LOST', label: 'LOST', tone: 'neutral' },
  { code: 'NO SE LOCALIZA DIRECCIÓN DEL DESTINATARIO', label: 'NO SE LOCALIZA DIRECCIÓN DEL DESTINATARIO', tone: 'neutral' },
  { code: 'NOVEDAD', label: 'NOVEDAD', tone: 'neutral' },
  { code: 'NOVEDAD SOLUCIONADA', label: 'NOVEDAD SOLUCIONADA', tone: 'mint' },
  { code: 'PEDIDO CANCELADO', label: 'PEDIDO CANCELADO', tone: 'neutral' },
  { code: 'PENDIENTE', label: 'PENDIENTE', tone: 'brand' },
  { code: 'POR RECOLECTAR', label: 'POR RECOLECTAR', tone: 'brand' },
  { code: 'PUNTO_DROOP', label: 'PUNTO_DROOP', tone: 'gold' },
  { code: 'RECHAZADO', label: 'RECHAZADO', tone: 'neutral' },
  { code: 'RECLAMACIONES', label: 'RECLAMACIONES', tone: 'neutral' },
  { code: 'RECLAME EN OFICINA', label: 'RECLAME EN OFICINA', tone: 'neutral' },
  { code: 'RECOGIDA FALLIDA', label: 'RECOGIDA FALLIDA', tone: 'neutral' },
  { code: 'RECOGIDO POR DROPI', label: 'RECOGIDO POR DROPI', tone: 'mint' },
  { code: 'REENVIO', label: 'REENVIO', tone: 'gold' },
  { code: 'SIN MOVIMIENTOS', label: 'SIN MOVIMIENTOS', tone: 'neutral' },
  { code: 'SINIESTRADO', label: 'SINIESTRADO', tone: 'neutral' },
  { code: 'TELEMERCADEO', label: 'TELEMERCADEO', tone: 'brand' },
] as const;

export const ORDER_STATUS_MAP = new Map(
  ORDER_STATUS_CATALOG.map((status) => [status.code, status] as const),
);
